### ISSUE TITLE
BrowserHTML not starting

### ISSUE THREAD

**Issue by Coder206** [browserhtml/browserhtml#1082]
I am unable to get Servo running on Linux or Windows using the command `./mach run -r --browserhtml`. 

On Fedora 23, I received an error message picture below:

![fedora23](https://cloud.githubusercontent.com/assets/7758155/15795434/80cc9394-29bf-11e6-8745-e87d2abe37bf.png)

On Windows 10, I receive a blank screen. (pictured below)
![w10](https://cloud.githubusercontent.com/assets/7758155/15795466/c92a7246-29bf-11e6-9012-6867995a126a.PNG)

Do you have any ideas of why this is happening? Has anyone experienced this before?

**Comment by Coder206** [comment]
Here is the result after using `npm run build-server`

"0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build-server' ]
2 info using npm@3.8.9
3 info using node@v6.2.0
4 verbose run-script [ 'prebuild-server', 'build-server', 'postbuild-server' ]
5 info lifecycle browser.html@0.1.7~prebuild-server: browser.html@0.1.7
6 silly lifecycle browser.html@0.1.7~prebuild-server: no script for prebuild-server, continuing
7 info lifecycle browser.html@0.1.7~build-server: browser.html@0.1.7
8 verbose lifecycle browser.html@0.1.7~build-server: unsafe-perm in lifecycle true
9 verbose lifecycle browser.html@0.1.7~build-server: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;E:\files\dev\GitHub\browserhtml\node_modules\.bin;C:\Program Files\nodejs;C:\Python27\;C:\Python27\Scripts;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\Rust stable GNU 1.9\bin;C:\Program Files\nodejs\;C:\Program Files\Git\cmd;;C:\Program Files (x86)\Microsoft VS Code\bin;C:\Users\Patrick\AppData\Roaming\npm
10 verbose lifecycle browser.html@0.1.7~build-server: CWD: E:\files\dev\GitHub\browserhtml
11 silly lifecycle browser.html@0.1.7~build-server: Args: [ '/d /s /c', 'gulp build-server' ]
12 silly lifecycle browser.html@0.1.7~build-server: Returned: code: 1  signal: null
13 info lifecycle browser.html@0.1.7~build-server: Failed to exec build-server script
14 verbose stack Error: browser.html@0.1.7 build-server: `gulp build-server`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:245:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:850:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
15 verbose pkgid browser.html@0.1.7
16 verbose cwd E:\files\dev\GitHub\browserhtml
17 error Windows_NT 10.0.10586
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build-server"
19 error node v6.2.0
20 error npm  v3.8.9
21 error code ELIFECYCLE
22 error browser.html@0.1.7 build-server: `gulp build-server`
22 error Exit status 1
23 error Failed at the browser.html@0.1.7 build-server script 'gulp build-server'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the browser.html package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     gulp build-server
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs browser.html
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls browser.html
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]"


***Please note, I am still having trouble getting Servo to build (using both the -d and -r flags)
