### ISSUE TITLE
"electron ." fails

### ISSUE THREAD

**Issue by sarenord** [browserhtml/browserhtml#1307]
running arch linux, latest everything, master branch

build went fine, npm run build-server works fine, i can access things from localhost:6060 in my web browser, but running "electron ." throws the folloing error:

'App threw an error during load
TypeError: Cannot read property 'setIcon' of undefined
    at Object.<anonymous> (/home/sarenord/git/browserhtml/main.js:90:9)
    at Object.<anonymous> (/home/sarenord/git/browserhtml/main.js:99:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at loadApplicationPackage (/usr/lib/electron/resources/default_app.asar/main.js:283:12)
    at Object.<anonymous> (/usr/lib/electron/resources/default_app.asar/main.js:325:5)
    at Object.<anonymous> (/usr/lib/electron/resources/default_app.asar/main.js:361:3)
A JavaScript error occurred in the main process
Uncaught Exception:
TypeError: Cannot read property 'setIcon' of undefined
    at Object.<anonymous> (/home/sarenord/git/browserhtml/main.js:90:9)
    at Object.<anonymous> (/home/sarenord/git/browserhtml/main.js:99:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at loadApplicationPackage (/usr/lib/electron/resources/default_app.asar/main.js:283:12)
    at Object.<anonymous> (/usr/lib/electron/resources/default_app.asar/main.js:325:5)
    at Object.<anonymous> (/usr/lib/electron/resources/default_app.asar/main.js:361:3)

(electron:6397): Gdk-WARNING **: gdkwindow-x11.c:5573 drawable is not a native X11 window

(electron:6397): Gdk-WARNING **: gdkwindow-x11.c:5573 drawable is not a native X11 window

(electron:6397): Gdk-WARNING **: gdkwindow-x11.c:5573 drawable is not a native X11 window
`

**Comment by Kilian** [comment]
Only MacOS has a dock, so it should be in an if-clause:

```
if (process.platform === 'darwin') {
    app.dock.setIcon(...);
}
```

**Comment by nextlevelshit** [comment]
@Kilian Are there already any PR's?

**Comment by Kilian** [comment]
@nextlevelshit not by me...This repository doesn't have a lot of activity it seems so I doubt any PR would be looked at.

**Comment by paulrouget** [comment]
This project has been retired: https://groups.google.com/d/msg/mozilla.dev.servo/U5zhsBLXovM/HbRL69zZBAAJ

**Comment by nextlevelshit** [comment]
@paulrouget Thanks! But it stays sad -.-
